Optimize rendering
2gis/markerdrawer pull request #1
Opened 2017-04-03 10:18 UTC by Trufi

* Теперь рендеринг происходит не за 1 кадр, а за несколько, за счет этого рендер луп не забивается отрисовкой
* Чтобы маркера не мелькали, сделал два канваса, один показывается пользователю, на другом скрыто происходит рендеринг
* Количество маркеров отрисовывающихся в конкретный фрейм считается адаптивно, так чтобы это не длилось больше 10ms

Остальное:
* Убрал методы `setMarkerIcon`, `setMarkersIcon`, если нужно поменять иконку маркера, то надо поменять `iconIndex` у объекта маркера и вызвать `markerDrawer.update()`
* Добавил метод `setMarkers`, чтобы менять весь массив рисующихся маркеров

2017-04-04 11:08 UTC, osvodef requested changes

2017-04-04 11:08 UTC, RLRR commented on src/CanvasRenderer.ts
> +        const markerSpeed = (now() - startTime) / (to - from);
Лучше было бы назвать переменную `timePerMarker`, а то по названию кажется, что это кол-во маркеров на единицу времени

2017-04-04 11:08 UTC, RLRR commented on src/CanvasRenderer.ts
> +    private _framesSwitch() {
А тут лучше `_switchFrames`

2017-04-04 11:08 UTC, RLRR commented on src/CanvasRenderer.ts
> +        this._currentFrame.canvas.style.display = 'none';
А почему тут `display: none` выставляется у текущего фрейма, а не у скрытого?

2017-04-04 11:08 UTC, RLRR commented on src/CanvasRenderer.ts
> +        this.container.appendChild(this._currentFrame.canvas);
И нужен ли здесь этот вызов `appendChild`? Он в `_createFrame` тоже делается

2017-04-04 11:21 UTC, Trufi commented on src/CanvasRenderer.ts
> +        this.container.appendChild(this._currentFrame.canvas);
Косяк

2017-04-05 08:17 UTC, Trufi commented
@RLRR поправил

2017-04-06 04:36 UTC, egoroof commented on src/CanvasRenderer.ts
> +        this._currentFrame.canvas.style.height = size[1] + 'px';
а зачем нужно размеры в стили выставлять, когда размеры заданы через атрибуты тега canvas?

2017-04-06 04:40 UTC, Trufi commented on src/CanvasRenderer.ts
> +        this._currentFrame.canvas.style.height = size[1] + 'px';
Хороший вопрос! И я не знаю, знаю только, что без этого работать не будет, особенно для ретины :)

2017-04-06 04:41 UTC, egoroof approved these changes

2017-04-06 04:43 UTC, egoroof commented
> Only reviews by reviewers with write access count toward mergeability

Этого репо нету в нашей команде гитхаба?

2017-04-06 04:45 UTC, Trufi commented on src/CanvasRenderer.ts
> +        this._currentFrame.canvas.style.height = size[1] + 'px';
В стилях указывается размеры канвас в логических пикселях, а в тэге в данном случае в физических, что полезно когда надо рендерить 2х для ретины.

2017-04-06 06:13 UTC, osvodef approved these changes

2017-04-06 06:33 UTC, Trufi commented
Добавил

2017-04-06 06:33 UTC, merged