add mouseout and mouseover + fix demo
2gis/markerdrawer pull request #17
Opened 2017-06-12 19:16 UTC by scherebedov

Добавил события `mouseout` и `mouseover`.
Предварительную проверку, что данный пиксель закрашен делать не стал.
По хорошему для правильной работы состояния маркера `active` (когда зажали мышку) нужно разделить `click` на `mouseup` и `mousedown`. + у меня при ховере берётся только верхний маркер, думаю имеет смысл сделать тоже самое и для клика.

2017-06-13 05:17 UTC, egoroof commented on src/MarkerDrawer.ts
> +        this._pane.addEventListener('click', this._onClick);
два события клик?

2017-06-13 09:18 UTC, scherebedov commented on src/MarkerDrawer.ts
> +        this._pane.addEventListener('click', this._onClick);
Время комита оправдывает лёгкую невинмательность :D Поправил )

2017-06-13 09:31 UTC, Trufi requested changes

2017-06-13 09:31 UTC, Trufi commented on src/MarkerDrawer.ts
> +            if (markers.length === 1) {
Это кейс точно надо обрабатывать?

2017-06-13 09:45 UTC, scherebedov commented on src/MarkerDrawer.ts
> +            if (markers.length === 1) {
Я подумал, что так будет лучше, что бы лишний раз не вызывать Math.max, хотя никакой разницы, сейчас проверил.

2017-06-13 09:48 UTC, egoroof commented on src/MarkerDrawer.ts
> +        this._pane.removeEventListener('click', this._onClick);
это тоже лишняя строка

2017-06-13 10:00 UTC, scherebedov commented on src/MarkerDrawer.ts
> +        this._pane.removeEventListener('click', this._onClick);
Доне

2017-06-13 10:03 UTC, Trufi requested changes

2017-06-13 10:03 UTC, Trufi commented on src/MarkerDrawer.ts
> +            topMarker = Math.max(...markers);
Теперь можно сделать `const`

2017-06-13 11:06 UTC, scherebedov commented
+ ко всему добавл события `mousedown` и `mouseup` + все события (и `click` тоже) теперь возвращают только верхний маркер.

2017-06-14 06:05 UTC, Trufi approved these changes

2017-06-15 05:03 UTC, egoroof approved these changes

2017-06-15 05:54 UTC, merged