Update atlas method
2gis/markerdrawer pull request #21
Opened 2017-06-26 10:18 UTC by scherebedov

Добавил метод для обновления атласа + уменьшил число первоначальной отрисовки маркеров до 1000.

2017-06-26 10:22 UTC, Trufi requested changes

2017-06-26 10:22 UTC, Trufi commented on src/CanvasRenderer.ts
> +    public updateAtlas(atlas: Atlas) {
Не усложняет ли понимание то, что атлас можно задать и через конструктор, и через метод?

2017-06-26 10:23 UTC, scherebedov commented on src/CanvasRenderer.ts
> +    public updateAtlas(atlas: Atlas) {
Да не, норм

2017-06-26 10:23 UTC, egoroof commented on src/CanvasRenderer.ts
> +        }
А может так?
```js
if (this._atlas) {
    return;
}
this._atlas.whenReady().then(this.update);
```

2017-06-26 10:36 UTC, egoroof approved these changes

2017-06-27 03:19 UTC, Trufi approved these changes

2017-06-27 03:19 UTC, merged