fix markers events on drag
2gis/markerdrawer pull request #34
Opened 2019-04-05 09:55 UTC by alxart

Добавил проверку на текущую кнопку мыши в событии: теперь при драге поиск индексов маркеров в rbush не прозводится, в событии клик теперь нельзя кликнуть на не-hovered маркер. В коде добавил подробные комменты.

2019-04-09 03:11 UTC, Trufi requested changes

2019-04-09 03:11 UTC, Trufi commented on src/MarkerDrawer.ts
> +         * описанная в https://jira.2gis.ru/browse/TILES-1878
Проект открытый, поэтому не стоит сюда вставлять ссылки из внутренней jira

2019-04-09 03:11 UTC, Trufi commented on src/MarkerDrawer.ts
> +        if (which === 1) {
Фикс неплохой, но мне кажется, что лучше подписаться на события `movestart` и `moveend` лифлета, т.к. ховеры должны перестать работать не только во время драга карты, а вообще при любом движении. Обработка этих событий уже есть в CanvasRenderer, может с помощью них эту ситуацию обрулить?

Кажется, что сейчас будет баг:
1. Сделать ховер на маркер
2. Драг карту так, чтобы после драга курсор слетел с маркера
ОР: Ховер на маркер пропадет
ФР: Ховер остался, хотя курсор уже не над маркером. Он пропадет только при следующем движении мыши.

2019-04-17 09:15 UTC, osvodef requested changes

2019-04-17 09:15 UTC, osvodef commented on src/CanvasRenderer.ts
> +        this.fire('treeisinvalid');
Названия событий обычно делают не предложениями, а словосочетаниями. Пример — `dragstart`, а не `draghasstarted`. Так что тут лучше будут смотреться названия `validtree` и `invalidtree`.

2019-04-18 06:31 UTC, Trufi requested changes

2019-04-18 06:31 UTC, Trufi commented on src/MarkerDrawer.ts
> +        if (this._isZooming) {
Зачем этот if нужен?

2019-04-18 06:31 UTC, Trufi commented on src/MarkerDrawer.ts
> +        this._renderer.on('treeisvalid', () => {
Почему некоторые обработчики ты выносишь в отдельные методы, а некоторые пишешь сразу?

2019-04-18 06:31 UTC, Trufi commented on src/MarkerDrawer.ts
> +    private _onDblClick = (ev: MouseEvent) => {
А зачем нужно обрабатывать события dblclick и mousewheel?

2019-04-18 07:40 UTC, alxart commented on src/MarkerDrawer.ts
> +        if (this._isZooming) {
На самом деле здесь его можно и не писать из-за логики "за zoomstart следует movestart". А так здесь видно, что мы завязаны именно на окончание зума, а не на любой move карты.

2019-04-18 07:48 UTC, alxart commented on src/MarkerDrawer.ts
> +        this._renderer.on('treeisvalid', () => {
Здесь же CanvasRenderer жестко привязан к MarkerDrawer, поэтому выносить это на логику удаления/добавления карты смысла нет.

2019-04-18 07:54 UTC, alxart commented on src/MarkerDrawer.ts
> +    private _onDblClick = (ev: MouseEvent) => {
Эти события однозначно вызовут move карты, но бросаются еще до того, как CanvasRenderer сообщит о невалидности rbush, только после которого мы начинаем сохранять текущее положение курсора. Поэтому если зумиться по двойному клику или колесу и не делать движение мышью, то будет невозможно отследить положение курсора.

2019-04-19 09:51 UTC, osvodef approved these changes

2019-04-19 11:07 UTC, Trufi requested changes

2019-04-19 11:07 UTC, Trufi commented on src/MarkerDrawer.ts
> +        if (this._isZooming) {
Я про то, что `_isZooming` может принимать всего 2 значения: либо `true`, либо `false`. При каких-либо его значениях не была вызвана эта функция, результат всегда будет один `_isZooming = false`. Тогда `if` не имеет смысла.

2019-04-22 07:48 UTC, Trufi approved these changes

2019-04-22 08:04 UTC, egoroof approved these changes

2019-04-23 09:56 UTC, merged