Less code
2gis/markerdrawer pull request #4
Opened 2017-04-07 04:07 UTC by scherebedov

Было `22.2 kB` стало `21.2 kB`

2017-04-07 04:42 UTC, Trufi requested changes

2017-04-07 04:42 UTC, Trufi commented on webpack.config.js
> +                    beautify: false,
Это дефолтное значение, можно не указывать

2017-04-07 04:42 UTC, Trufi commented on webpack.config.js
> +                        unsafe: true
Это тоже все дефолтные параметры, кроме:
`unsafe: true` – кажется, делать это опасно, если мы не хотим словить странные баги
`warnings: false` – не влияет на сборку, но может быть полезным, к тому же, кажется, вебпак не выводит эти сообщения
`drop_console: true` – бесполезен, у нас использование console линтер не пропустит

2017-04-07 04:42 UTC, Trufi commented on src/CanvasRenderer.ts
> +        if (typeof production === 'undefined') {
Тут надо подумать, не хотелось бы, чтобы для включения рисования оффсетов в генерале, нам нужно было бы пересобирать markder drawer для него

2017-04-07 04:42 UTC, Trufi commented on webpack.config.js
> +                    production: true
Кажется, что такие штуки лучше делать через EnvironmentPlugin

2017-04-07 07:20 UTC, scherebedov commented on src/CanvasRenderer.ts
> +        if (typeof production === 'undefined') {
Ну в продакшене этот код точно не будет нужен.

2017-04-07 07:20 UTC, scherebedov commented on webpack.config.js
> +                        unsafe: true
`unsafe: true` ничего страшного не сделал, всё работает

2017-04-12 04:23 UTC, scherebedov commented
Ну я закрываю тогда )

2017-04-12 04:23 UTC, closed without merging

2017-04-12 05:52 UTC, Trufi commented
Зря закрыл, надо нам везде так попробовать сделать, и посмотреть, сколько сможем выиграть